# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def23a94ca57bf4ab1360cb068d5e2806961be327bc27bd895a9804758a273b835d8b8da5842f8e1cad2ca0059c0b911d2703dc9c2c17b439b2be3e25c7ed667

test:
  secret_key_base: b4d4b17f6e7be31188a5be2c46502148a073de316165313f7d89b9bec8f727d6f7751bdc32e03e91382d42923c99920faff9c649c60262078f00ae529d7f8214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
